// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:game_saves_backup/core/sync/repositories/items_repository.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(BackupItemAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(BackupItemAdapter());
  }
}
